/* EDIT ME */

// CLIENT CODE
if ( isDedicated ) exitWith {};

// WAIT UNTIL PLAYER VARIABLE HAS BEEN INITIALIZED ON THE CLIENT'S MACHINE
waitUntil { !( isNull player ) };

/* EDIT PAST HERE */

/* VEHICLE TYPE BUILD DELAYS ( RECOMMEND A MINIMUM OF 2 SECOND DELAY ) */
VSYS_DELAY_AIR	 = 2;
VSYS_DELAY_ARMORED = 2;
VSYS_DELAY_CAR	 = 2;
VSYS_DELAY_SUPPORT = 2;
VSYS_DELAY_DEFAULT = 2;



/* 
	-- INPUT WHICH SIDE(S) VEHICLES YOU WANT VSYS TO DISPLAY...
	
	... AS AN ARRAY OF (NUMBERS) SIDE ID'S.  
	- 0 = EAST 
	- 1 = WEST
	- 2 = INDEPENDENT

	EXAMPLES:
	NOTE: BIS_fnc_sideID RETURNS THE PLAYER'S SIDE ID (NUMBER).
		
	VSYS_SIDES = [ 0, 2 ]; << SHOW EAST AND INDEPENDENT VEHICLES
	VSYS_SIDES = [ [ side player ] call BIS_fnc_sideID ]; << SHOW ONLY YOUR SIDES VEHICLES
	VSYS_SIDES = [ [ side player ] call BIS_fnc_sideID, 0, 1, 2 ]; << SHOW YOUR SIDES VEHICLES + ALL SIDES VEHICLES
	VSYS_SIDES = [ [ side player ] call BIS_fnc_sideID, 2 ]; << SHOW YOUR SIDES VEHICLES + INDEPENDENT SIDE VEHICLES

*/

// ATM I ONLY WANT TO DISPLAY MY SIDE'S VEHICLES AND NO ONE ELSES
VSYS_SIDES = [ [ side player ] call BIS_fnc_sideID ];

/* DON'T EDIT PAST HERE */



/* 
	-- DISPLAY AND CONTROLS DEFINES --
	-- SHOULDN'T HAVE TO FIDDLE WITH THESE. ANYHOW... 
	-- ONLY ADJUST THESE VALUES IF YOU'RE GETTING CONFLICTS WITH OTHER CUSTOM CONTROL IDCS ( IE; MEMBER ALREADY DEFINED CTD ERROR ) --	
*/


// MAIN DISPLAY 
IDD_DISPLAY_MAIN   	=     100500;

// BUTTONS
IDC_BTN_CREATE    	=     200500;
IDC_BTN_CANCEL 	 	= 	  200501;

// PROGRESS BARS
IDC_PROGRESS_MAIN  	= 	  300500;

// LISTBOXES
IDC_LISTBOX_MAIN   	= 	  400500;

// TEXTS
IDC_TEXT_PROGRESS     =     500500;

// ACTIVE TEXTS
IDC_ACTIVET_AIR 	  	= 	  600500;
IDC_ACTIVET_ARMOR   	= 	  600501;
IDC_ACTIVET_CAR    	= 	  600502;
IDC_ACTIVET_SUPPORT 	= 	  600503;

// CHECK BOXES
IDC_CB_CREW        	=     700500;
IDC_CB_FLYING        	=     700501;
IDC_CB_GETIN         	=     700502;